missing module named resource - imported by posix, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named posix - imported by os, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named 'org.python' - imported by pickle, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py, xml.sax
missing module named ce - imported by os, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named readline - imported by cmd, code, pdb, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
excluded module named _frozen_importlib - imported by importlib, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named 'java.lang' - imported by platform, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named termios - imported by tty, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py, getpass
missing module named grp - imported by tarfile, shutil, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py, getpass
missing module named org - imported by copy, C:\Users\T450S\workspace\PY_CYP\R9Match_ULDL_JAKO\r9_modify_error_data.py
